/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "service.pb-c.h"
void   hint__init
                     (Hint         *message)
{
  static const Hint init_value = HINT__INIT;
  *message = init_value;
}
size_t hint__get_packed_size
                     (const Hint *message)
{
  assert(message->base.descriptor == &hint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hint__pack
                     (const Hint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hint__pack_to_buffer
                     (const Hint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hint *
       hint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hint *)
     protobuf_c_message_unpack (&hint__descriptor,
                                allocator, len, data);
}
void   hint__free_unpacked
                     (Hint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   symbol__init
                     (Symbol         *message)
{
  static const Symbol init_value = SYMBOL__INIT;
  *message = init_value;
}
size_t symbol__get_packed_size
                     (const Symbol *message)
{
  assert(message->base.descriptor == &symbol__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t symbol__pack
                     (const Symbol *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &symbol__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t symbol__pack_to_buffer
                     (const Symbol *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &symbol__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Symbol *
       symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Symbol *)
     protobuf_c_message_unpack (&symbol__descriptor,
                                allocator, len, data);
}
void   symbol__free_unpacked
                     (Symbol *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &symbol__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   section_hash__init
                     (SectionHash         *message)
{
  static const SectionHash init_value = SECTION_HASH__INIT;
  *message = init_value;
}
size_t section_hash__get_packed_size
                     (const SectionHash *message)
{
  assert(message->base.descriptor == &section_hash__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t section_hash__pack
                     (const SectionHash *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &section_hash__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t section_hash__pack_to_buffer
                     (const SectionHash *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &section_hash__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SectionHash *
       section_hash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SectionHash *)
     protobuf_c_message_unpack (&section_hash__descriptor,
                                allocator, len, data);
}
void   section_hash__free_unpacked
                     (SectionHash *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &section_hash__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   binary__init
                     (Binary         *message)
{
  static const Binary init_value = BINARY__INIT;
  *message = init_value;
}
size_t binary__get_packed_size
                     (const Binary *message)
{
  assert(message->base.descriptor == &binary__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t binary__pack
                     (const Binary *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &binary__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t binary__pack_to_buffer
                     (const Binary *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &binary__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Binary *
       binary__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Binary *)
     protobuf_c_message_unpack (&binary__descriptor,
                                allocator, len, data);
}
void   binary__free_unpacked
                     (Binary *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &binary__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   signature__init
                     (Signature         *message)
{
  static const Signature init_value = SIGNATURE__INIT;
  *message = init_value;
}
size_t signature__get_packed_size
                     (const Signature *message)
{
  assert(message->base.descriptor == &signature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t signature__pack
                     (const Signature *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &signature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t signature__pack_to_buffer
                     (const Signature *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &signature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Signature *
       signature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Signature *)
     protobuf_c_message_unpack (&signature__descriptor,
                                allocator, len, data);
}
void   signature__free_unpacked
                     (Signature *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &signature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   share_symbol__init
                     (ShareSymbol         *message)
{
  static const ShareSymbol init_value = SHARE_SYMBOL__INIT;
  *message = init_value;
}
size_t share_symbol__get_packed_size
                     (const ShareSymbol *message)
{
  assert(message->base.descriptor == &share_symbol__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t share_symbol__pack
                     (const ShareSymbol *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &share_symbol__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t share_symbol__pack_to_buffer
                     (const ShareSymbol *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &share_symbol__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShareSymbol *
       share_symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShareSymbol *)
     protobuf_c_message_unpack (&share_symbol__descriptor,
                                allocator, len, data);
}
void   share_symbol__free_unpacked
                     (ShareSymbol *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &share_symbol__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   share_section__init
                     (ShareSection         *message)
{
  static const ShareSection init_value = SHARE_SECTION__INIT;
  *message = init_value;
}
size_t share_section__get_packed_size
                     (const ShareSection *message)
{
  assert(message->base.descriptor == &share_section__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t share_section__pack
                     (const ShareSection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &share_section__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t share_section__pack_to_buffer
                     (const ShareSection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &share_section__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShareSection *
       share_section__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShareSection *)
     protobuf_c_message_unpack (&share_section__descriptor,
                                allocator, len, data);
}
void   share_section__free_unpacked
                     (ShareSection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &share_section__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   share_bin__init
                     (ShareBin         *message)
{
  static const ShareBin init_value = SHARE_BIN__INIT;
  *message = init_value;
}
size_t share_bin__get_packed_size
                     (const ShareBin *message)
{
  assert(message->base.descriptor == &share_bin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t share_bin__pack
                     (const ShareBin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &share_bin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t share_bin__pack_to_buffer
                     (const ShareBin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &share_bin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShareBin *
       share_bin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShareBin *)
     protobuf_c_message_unpack (&share_bin__descriptor,
                                allocator, len, data);
}
void   share_bin__free_unpacked
                     (ShareBin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &share_bin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message__init
                     (Message         *message)
{
  static const Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   match_hints__init
                     (MatchHints         *message)
{
  static const MatchHints init_value = MATCH_HINTS__INIT;
  *message = init_value;
}
size_t match_hints__get_packed_size
                     (const MatchHints *message)
{
  assert(message->base.descriptor == &match_hints__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t match_hints__pack
                     (const MatchHints *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &match_hints__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t match_hints__pack_to_buffer
                     (const MatchHints *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &match_hints__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MatchHints *
       match_hints__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MatchHints *)
     protobuf_c_message_unpack (&match_hints__descriptor,
                                allocator, len, data);
}
void   match_hints__free_unpacked
                     (MatchHints *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &match_hints__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hint__field_descriptors[2] =
{
  {
    "bits",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Hint, bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Hint, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hint__field_indices_by_name[] = {
  0,   /* field[0] = bits */
  1,   /* field[1] = offset */
};
static const ProtobufCIntRange hint__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hint__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Hint",
  "Hint",
  "Hint",
  "",
  sizeof(Hint),
  2,
  hint__field_descriptors,
  hint__field_indices_by_name,
  1,  hint__number_ranges,
  (ProtobufCMessageInit) hint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor symbol__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Symbol, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Symbol, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callconv",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Symbol, callconv),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bits",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Symbol, bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned symbol__field_indices_by_name[] = {
  3,   /* field[3] = bits */
  2,   /* field[2] = callconv */
  0,   /* field[0] = name */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange symbol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor symbol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Symbol",
  "Symbol",
  "Symbol",
  "",
  sizeof(Symbol),
  4,
  symbol__field_descriptors,
  symbol__field_indices_by_name,
  1,  symbol__number_ranges,
  (ProtobufCMessageInit) symbol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor section_hash__field_descriptors[2] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SectionHash, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "digest",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SectionHash, digest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned section_hash__field_indices_by_name[] = {
  1,   /* field[1] = digest */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange section_hash__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor section_hash__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SectionHash",
  "SectionHash",
  "SectionHash",
  "",
  sizeof(SectionHash),
  2,
  section_hash__field_descriptors,
  section_hash__field_indices_by_name,
  1,  section_hash__number_ranges,
  (ProtobufCMessageInit) section_hash__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor binary__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Binary, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Binary, os),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sections",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Binary, n_sections),
    offsetof(Binary, sections),
    &section_hash__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned binary__field_indices_by_name[] = {
  1,   /* field[1] = os */
  2,   /* field[2] = sections */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange binary__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor binary__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Binary",
  "Binary",
  "Binary",
  "",
  sizeof(Binary),
  3,
  binary__field_descriptors,
  binary__field_indices_by_name,
  1,  binary__number_ranges,
  (ProtobufCMessageInit) binary__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor signature__field_descriptors[4] =
{
  {
    "arch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Signature, arch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bits",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Signature, bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Signature, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "digest",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Signature, digest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned signature__field_indices_by_name[] = {
  0,   /* field[0] = arch */
  1,   /* field[1] = bits */
  3,   /* field[3] = digest */
  2,   /* field[2] = length */
};
static const ProtobufCIntRange signature__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor signature__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Signature",
  "Signature",
  "Signature",
  "",
  sizeof(Signature),
  4,
  signature__field_descriptors,
  signature__field_indices_by_name,
  1,  signature__number_ranges,
  (ProtobufCMessageInit) signature__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor share_symbol__field_descriptors[2] =
{
  {
    "symbol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShareSymbol, symbol),
    &symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShareSymbol, signature),
    &signature__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned share_symbol__field_indices_by_name[] = {
  1,   /* field[1] = signature */
  0,   /* field[0] = symbol */
};
static const ProtobufCIntRange share_symbol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor share_symbol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShareSymbol",
  "ShareSymbol",
  "ShareSymbol",
  "",
  sizeof(ShareSymbol),
  2,
  share_symbol__field_descriptors,
  share_symbol__field_indices_by_name,
  1,  share_symbol__number_ranges,
  (ProtobufCMessageInit) share_symbol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor share_section__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShareSection, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShareSection, section),
    &section_hash__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hints",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShareSection, n_hints),
    offsetof(ShareSection, hints),
    &hint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned share_section__field_indices_by_name[] = {
  2,   /* field[2] = hints */
  0,   /* field[0] = name */
  1,   /* field[1] = section */
};
static const ProtobufCIntRange share_section__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor share_section__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShareSection",
  "ShareSection",
  "ShareSection",
  "",
  sizeof(ShareSection),
  3,
  share_section__field_descriptors,
  share_section__field_indices_by_name,
  1,  share_section__number_ranges,
  (ProtobufCMessageInit) share_section__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor share_bin__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShareBin, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShareBin, os),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sections",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShareBin, n_sections),
    offsetof(ShareBin, sections),
    &share_section__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbols",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShareBin, n_symbols),
    offsetof(ShareBin, symbols),
    &share_symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned share_bin__field_indices_by_name[] = {
  1,   /* field[1] = os */
  2,   /* field[2] = sections */
  3,   /* field[3] = symbols */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange share_bin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor share_bin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShareBin",
  "ShareBin",
  "ShareBin",
  "",
  sizeof(ShareBin),
  4,
  share_bin__field_descriptors,
  share_bin__field_indices_by_name,
  1,  share_bin__number_ranges,
  (ProtobufCMessageInit) share_bin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[4] =
{
  {
    "psk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Request, psk),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, route),
    &route__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  3,   /* field[3] = message */
  0,   /* field[0] = psk */
  2,   /* field[2] = route */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  4,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Message, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  1,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor match_hints__field_descriptors[1] =
{
  {
    "hints",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MatchHints, n_hints),
    offsetof(MatchHints, hints),
    &hint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned match_hints__field_indices_by_name[] = {
  0,   /* field[0] = hints */
};
static const ProtobufCIntRange match_hints__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor match_hints__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MatchHints",
  "MatchHints",
  "MatchHints",
  "",
  sizeof(MatchHints),
  1,
  match_hints__field_descriptors,
  match_hints__field_indices_by_name,
  1,  match_hints__number_ranges,
  (ProtobufCMessageInit) match_hints__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Response, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue route__enum_values_by_number[4] =
{
  { "PING", "ROUTE__PING", 0 },
  { "BINARY", "ROUTE__BINARY", 1 },
  { "SIGNATURE", "ROUTE__SIGNATURE", 2 },
  { "SHARE_BIN", "ROUTE__SHARE_BIN", 3 },
};
static const ProtobufCIntRange route__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex route__enum_values_by_name[4] =
{
  { "BINARY", 1 },
  { "PING", 0 },
  { "SHARE_BIN", 3 },
  { "SIGNATURE", 2 },
};
const ProtobufCEnumDescriptor route__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Route",
  "Route",
  "Route",
  "",
  4,
  route__enum_values_by_number,
  4,
  route__enum_values_by_name,
  1,
  route__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue status__enum_values_by_number[8] =
{
  { "INTERNAL_ERROR", "STATUS__INTERNAL_ERROR", 0 },
  { "CLIENT_BAD_PRE_SHARED_KEY", "STATUS__CLIENT_BAD_PRE_SHARED_KEY", 1 },
  { "CLIENT_NOT_AUTHORIZED", "STATUS__CLIENT_NOT_AUTHORIZED", 2 },
  { "VERSION_MISMATCH", "STATUS__VERSION_MISMATCH", 3 },
  { "SHARE_WAS_SUCCESSFUL", "STATUS__SHARE_WAS_SUCCESSFUL", 4 },
  { "MESSAGE", "STATUS__MESSAGE", 5 },
  { "HINTS", "STATUS__HINTS", 6 },
  { "SYMBOL", "STATUS__SYMBOL", 7 },
};
static const ProtobufCIntRange status__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex status__enum_values_by_name[8] =
{
  { "CLIENT_BAD_PRE_SHARED_KEY", 1 },
  { "CLIENT_NOT_AUTHORIZED", 2 },
  { "HINTS", 6 },
  { "INTERNAL_ERROR", 0 },
  { "MESSAGE", 5 },
  { "SHARE_WAS_SUCCESSFUL", 4 },
  { "SYMBOL", 7 },
  { "VERSION_MISMATCH", 3 },
};
const ProtobufCEnumDescriptor status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Status",
  "Status",
  "Status",
  "",
  8,
  status__enum_values_by_number,
  8,
  status__enum_values_by_name,
  1,
  status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
